# Setting up Travis CI:

# 1. Go to https://travis-ci.org
# 2. Click the Sign Up/Sign in with GitHub button and give Travis CI permission
#    to access your GitHub repositories.
# 3. Create a file like this one you're reading at `your-rails-app/.travis.yml`:

language: ruby
rvm:
  - 2.2.2
  # Add more Ruby versions to list if supported,
  # Travis supports these versions: http://rubies.travis-ci.org/

before_script:
  - psql -c 'create database stack_overflow_clone_test;' -U postgres

  